/**
 * MaNGOS is a full featured server for World of Warcraft, supporting
 * the following clients: 1.12.x, 2.4.3, 3.3.5a, 4.3.4a and 5.4.8
 *
 * Copyright (C) 2005-2025 MaNGOS <https://www.getmangos.eu>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * World of Warcraft, and all World of Warcraft or Warcraft art, images,
 * and lore are copyrighted by Blizzard Entertainment, Inc.
 */

/**
 * @file ItemHandler.cpp
 * @brief Item inventory and interaction opcode handlers
 *
 * This file handles item-related opcodes including:
 * - CMSG_SPLIT_ITEM: Split item stack
 * - CMSG_SWAP_ITEM: Swap items between inventory slots
 * - CMSG_SWAP_INV_ITEM: Swap inventory items
 * - CMSG_DESTROYITEM: Destroy item
 * - CMSG_AUTOEQUIP_ITEM: Auto-equip item
 * - CMSG_ITEM_NAME_QUERY: Query item name
 * - CMSG_READ_ITEM: Read item (books, scrolls)
 * - CMSG_WRAP_ITEM: Wrap item with gift wrap
 * - CMSG_USE_ITEM: Use item (consume, equip, etc.)
 * - CMSG_OPEN_ITEM: Open item (containers)
 * - CMSG_BUY_ITEM: Buy item from vendor
 * - CMSG_SELL_ITEM: Sell item to vendor
 * - CMSG_REPAIR_ITEM: Repair item
 */

#include "Common.h"
#include "WorldPacket.h"
#include "WorldSession.h"
#include "Opcodes.h"
#include "Log.h"
#include "ObjectMgr.h"
#include "Player.h"
#include "Item.h"
#include "UpdateData.h"
#include "Chat.h"

/**
 * @brief Splits part of an item stack into another destination slot.
 *
 * @param recv_data The received opcode packet.
 */
void WorldSession::HandleSplitItemOpcode(WorldPacket& recv_data)
{
    // DEBUG_LOG("WORLD: CMSG_SPLIT_ITEM");
    uint8 srcbag, srcslot, dstbag, dstslot;
    uint32 count;

    recv_data >> srcbag >> srcslot >> dstbag >> dstslot >> count;
    // DEBUG_LOG("STORAGE: receive srcbag = %u, srcslot = %u, dstbag = %u, dstslot = %u, count = %u", srcbag, srcslot, dstbag, dstslot, count);

    uint16 src = ((srcbag << 8) | srcslot);
    uint16 dst = ((dstbag << 8) | dstslot);

    if (src == dst)
    {
        return;
    }

    if (count == 0)
    {
        return;                                             // check count - if zero it's fake packet
    }

    if (!_player->IsValidPos(srcbag, srcslot, true))
    {
        _player->SendEquipError(EQUIP_ERR_ITEM_NOT_FOUND, NULL, NULL);
        return;
    }

    if (!_player->IsValidPos(dstbag, dstslot, false))       // can be autostore pos
    {
        _player->SendEquipError(EQUIP_ERR_ITEM_DOESNT_GO_TO_SLOT, NULL, NULL);
        return;
    }

    _player->SplitItem(src, dst, count);
}

/**
 * @brief Swaps two equipped inventory slots.
 *
 * @param recv_data The received opcode packet.
 */
void WorldSession::HandleSwapInvItemOpcode(WorldPacket& recv_data)
{
    // DEBUG_LOG("WORLD: CMSG_SWAP_INV_ITEM");
    uint8 srcslot, dstslot;

    recv_data >> dstslot >> srcslot;
    // DEBUG_LOG("STORAGE: receive srcslot = %u, dstslot = %u", srcslot, dstslot);

    // prevent attempt swap same item to current position generated by client at special cheating sequence
    if (srcslot == dstslot)
    {
        return;
    }

    if (!_player->IsValidPos(INVENTORY_SLOT_BAG_0, srcslot, true))
    {
        _player->SendEquipError(EQUIP_ERR_ITEM_NOT_FOUND, NULL, NULL);
        return;
    }

    if (!_player->IsValidPos(INVENTORY_SLOT_BAG_0, dstslot, true))
    {
        _player->SendEquipError(EQUIP_ERR_ITEM_DOESNT_GO_TO_SLOT, NULL, NULL);
        return;
    }

    uint16 src = ((INVENTORY_SLOT_BAG_0 << 8) | srcslot);
    uint16 dst = ((INVENTORY_SLOT_BAG_0 << 8) | dstslot);

    _player->SwapItem(src, dst);
}

/**
 * @brief Equips an item into a specific equipment slot.
 *
 * @param recv_data The received opcode packet.
 */
void WorldSession::HandleAutoEquipItemSlotOpcode(WorldPacket& recv_data)
{
    ObjectGuid itemGuid;
    uint8 dstslot;
    recv_data >> itemGuid >> dstslot;

    // cheating attempt, client should never send opcode in that case
    if (!Player::IsEquipmentPos(INVENTORY_SLOT_BAG_0, dstslot))
    {
        return;
    }

    Item* item = _player->GetItemByGuid(itemGuid);
    uint16 dstpos = dstslot | (INVENTORY_SLOT_BAG_0 << 8);

    if (!item || item->GetPos() == dstpos)
    {
        return;
    }

    _player->SwapItem(item->GetPos(), dstpos);
}

/**
 * @brief Swaps two arbitrary item positions.
 *
 * @param recv_data The received opcode packet.
 */
void WorldSession::HandleSwapItem(WorldPacket& recv_data)
{
    // DEBUG_LOG("WORLD: CMSG_SWAP_ITEM");
    uint8 dstbag, dstslot, srcbag, srcslot;

    recv_data >> dstbag >> dstslot >> srcbag >> srcslot ;
    // DEBUG_LOG("STORAGE: receive srcbag = %u, srcslot = %u, dstbag = %u, dstslot = %u", srcbag, srcslot, dstbag, dstslot);

    uint16 src = ((srcbag << 8) | srcslot);
    uint16 dst = ((dstbag << 8) | dstslot);

    // prevent attempt swap same item to current position generated by client at special cheating sequence
    if (src == dst)
    {
        return;
    }

    if (!_player->IsValidPos(srcbag, srcslot, true))
    {
        _player->SendEquipError(EQUIP_ERR_ITEM_NOT_FOUND, NULL, NULL);
        return;
    }

    if (!_player->IsValidPos(dstbag, dstslot, true))
    {
        _player->SendEquipError(EQUIP_ERR_ITEM_DOESNT_GO_TO_SLOT, NULL, NULL);
        return;
    }

    _player->SwapItem(src, dst);
}

/**
 * @brief Auto-equips an item from inventory or bank.
 *
 * @param recv_data The received opcode packet.
 */
void WorldSession::HandleAutoEquipItemOpcode(WorldPacket& recv_data)
{
    // DEBUG_LOG("WORLD: CMSG_AUTOEQUIP_ITEM");
    uint8 srcbag, srcslot;

    recv_data >> srcbag >> srcslot;
    // DEBUG_LOG("STORAGE: receive srcbag = %u, srcslot = %u", srcbag, srcslot);

    Item* pSrcItem  = _player->GetItemByPos(srcbag, srcslot);
    if (!pSrcItem)
    {
        return;                                             // only at cheat
    }

    uint16 dest;
    InventoryResult msg = _player->CanEquipItem(NULL_SLOT, dest, pSrcItem, !pSrcItem->IsBag());
    if (msg != EQUIP_ERR_OK)
    {
        _player->SendEquipError(msg, pSrcItem, NULL);
        return;
    }

    uint16 src = pSrcItem->GetPos();
    if (dest == src)                                        // prevent equip in same slot, only at cheat
    {
        return;
    }

    Item* pDstItem = _player->GetItemByPos(dest);
    if (!pDstItem)                                          // empty slot, simple case
    {
        _player->RemoveItem(srcbag, srcslot, true);
        _player->EquipItem(dest, pSrcItem, true);
        _player->AutoUnequipOffhandIfNeed();
    }
    else                                                    // have currently equipped item, not simple case
    {
        uint8 dstbag = pDstItem->GetBagSlot();
        uint8 dstslot = pDstItem->GetSlot();

        msg = _player->CanUnequipItem(dest, !pSrcItem->IsBag());
        if (msg != EQUIP_ERR_OK)
        {
            _player->SendEquipError(msg, pDstItem, NULL);
            return;
        }

        // check dest->src move possibility
        ItemPosCountVec sSrc;
        uint16 eSrc = 0;
        if (_player->IsInventoryPos(src))
        {
            msg = _player->CanStoreItem(srcbag, srcslot, sSrc, pDstItem, true);
            if (msg != EQUIP_ERR_OK)
            {
                msg = _player->CanStoreItem(srcbag, NULL_SLOT, sSrc, pDstItem, true);
            }
            if (msg != EQUIP_ERR_OK)
            {
                msg = _player->CanStoreItem(NULL_BAG, NULL_SLOT, sSrc, pDstItem, true);
            }
        }
        else if (_player->IsBankPos(src))
        {
            msg = _player->CanBankItem(srcbag, srcslot, sSrc, pDstItem, true);
            if (msg != EQUIP_ERR_OK)
            {
                msg = _player->CanBankItem(srcbag, NULL_SLOT, sSrc, pDstItem, true);
            }
            if (msg != EQUIP_ERR_OK)
            {
                msg = _player->CanBankItem(NULL_BAG, NULL_SLOT, sSrc, pDstItem, true);
            }
        }
        else if (_player->IsEquipmentPos(src))
        {
            msg = _player->CanEquipItem(srcslot, eSrc, pDstItem, true);
            if (msg == EQUIP_ERR_OK)
            {
                msg = _player->CanUnequipItem(eSrc, true);
            }
        }

        if (msg != EQUIP_ERR_OK)
        {
            _player->SendEquipError(msg, pDstItem, pSrcItem);
            return;
        }

        // now do moves, remove...
        _player->RemoveItem(dstbag, dstslot, false);
        _player->RemoveItem(srcbag, srcslot, false);

        // add to dest
        _player->EquipItem(dest, pSrcItem, true);

        // add to src
        if (_player->IsInventoryPos(src))
        {
            _player->StoreItem(sSrc, pDstItem, true);
        }
        else if (_player->IsBankPos(src))
        {
            _player->BankItem(sSrc, pDstItem, true);
        }
        else if (_player->IsEquipmentPos(src))
        {
            _player->EquipItem(eSrc, pDstItem, true);
        }

        _player->AutoUnequipOffhandIfNeed();
    }
}

/**
 * @brief Destroys all or part of an item stack.
 *
 * @param recv_data The received opcode packet.
 */
void WorldSession::HandleDestroyItemOpcode(WorldPacket& recv_data)
{
    // DEBUG_LOG("WORLD: CMSG_DESTROYITEM");
    uint8 bag, slot, count, data1, data2, data3;

    recv_data >> bag >> slot >> count >> data1 >> data2 >> data3;
    // DEBUG_LOG("STORAGE: receive bag = %u, slot = %u, count = %u", bag, slot, count);

    uint16 pos = (bag << 8) | slot;

    // prevent drop unequipable items (in combat, for example) and non-empty bags
    if (_player->IsEquipmentPos(pos) || _player->IsBagPos(pos))
    {
        InventoryResult msg = _player->CanUnequipItem(pos, false);
        if (msg != EQUIP_ERR_OK)
        {
            _player->SendEquipError(msg, _player->GetItemByPos(pos), NULL);
            return;
        }
    }

    Item* pItem  = _player->GetItemByPos(bag, slot);
    if (!pItem)
    {
        _player->SendEquipError(EQUIP_ERR_ITEM_NOT_FOUND, NULL, NULL);
        return;
    }

    // checked at client side and not have server side appropriate error output
    if (pItem->GetProto()->Flags & ITEM_FLAG_INDESTRUCTIBLE)
    {
        _player->SendEquipError(EQUIP_ERR_CANT_DROP_SOULBOUND, NULL, NULL);
        return;
    }

    if (count)
    {
        uint32 i_count = count;
        _player->DestroyItemCount(pItem, i_count, true);
    }
    else
    {
        _player->DestroyItem(bag, slot, true);
    }
}

/**
 * @brief Handles a request to read a readable item.
 *
 * @param recv_data The received opcode packet.
 */
void WorldSession::HandleReadItemOpcode(WorldPacket& recv_data)
{
    // DEBUG_LOG("WORLD: Received opcode CMSG_READ_ITEM");

    uint8 bag, slot;
    recv_data >> bag >> slot;

    // sLog.outDetail("STORAGE: Read bag = %u, slot = %u", bag, slot);
    Item* pItem = _player->GetItemByPos(bag, slot);

    if (pItem && pItem->GetProto()->PageText)
    {
        WorldPacket data;

        InventoryResult msg = _player->CanUseItem(pItem);
        if (msg == EQUIP_ERR_OK)
        {
            data.Initialize(SMSG_READ_ITEM_OK, 8);
            DETAIL_LOG("STORAGE: Item page sent");
        }
        else
        {
            data.Initialize(SMSG_READ_ITEM_FAILED, 8);
            DETAIL_LOG("STORAGE: Unable to read item");
            _player->SendEquipError(msg, pItem, NULL);
        }
        data << pItem->GetObjectGuid();
        SendPacket(&data);
    }
    else
    {
        _player->SendEquipError(EQUIP_ERR_ITEM_NOT_FOUND, NULL, NULL);
    }
}

/**
 * @brief Logs a skipped page text query packet.
 *
 * @param recv_data The received opcode packet.
 */
void WorldSession::HandlePageQuerySkippedOpcode(WorldPacket& recv_data)
{
    DEBUG_LOG("WORLD: Received opcode CMSG_PAGE_TEXT_QUERY");

    uint32 itemid;
    ObjectGuid guid;

    recv_data >> itemid >> guid;

    DETAIL_LOG("Packet Info: itemid: %u guid: %s", itemid, guid.GetString().c_str());
}

void WorldSession::HandleItemRefundInfoRequest(WorldPacket& recv_data)
{
    DEBUG_LOG("WORLD: CMSG_ITEM_REFUND_INFO_REQUEST");

    ObjectGuid itemGuid;
    recv_data >> itemGuid;

    Item* item = _player->GetItemByGuid(itemGuid);

    if (!item)
    {
        DEBUG_LOG("Item refund: item not found!");
        return;
    }

    if (!(item->GetProto()->Flags & ITEM_FLAG_REFUNDABLE))
    {
        DEBUG_LOG("Item refund: item not refundable!");
        return;
    }

    ItemPrototype const* proto = item->GetProto();

    // Calculate remaining refund time (2 hours from purchase)
    uint32 createPlayedTime = item->GetUInt32Value(ITEM_FIELD_CREATE_PLAYED_TIME);
    uint32 curPlayedTime = _player->GetTotalPlayedTime();
    uint32 maxRefundTime = 2 * HOUR;
    uint32 remainingTime = 0;
    if (curPlayedTime - createPlayedTime < maxRefundTime)
    {
        remainingTime = maxRefundTime - (curPlayedTime - createPlayedTime);
    }

    // Send SMSG_SET_ITEM_PURCHASE_DATA
    // 5 currency slots + 5 item slots in extended cost structure
    WorldPacket data(SMSG_SET_ITEM_PURCHASE_DATA, 8 + 4 + 4 * 5 * 2 + 4 * 5 * 2 + 4);
    data << itemGuid;
    data << uint32(remainingTime);

    // Currency/token costs (from extended cost, 5 slots)
    for (uint32 i = 0; i < 5; ++i)
    {
        data << uint32(0);                                  // currency id
        data << uint32(0);                                  // currency count
    }

    // Item costs (from extended cost, 5 slots)
    for (uint32 i = 0; i < 5; ++i)
    {
        data << uint32(0);                                  // item id
        data << uint32(0);                                  // item count
    }

    data << uint32(proto->BuyPrice);                        // money cost

    SendPacket(&data);
}

/*
 * Handles the packet sent by the client when requesting information about item text.
 *
 * This function is called when player clicks on item which has some flag set
 */
void WorldSession::HandleItemTextQuery(WorldPacket& recv_data)
{
    ObjectGuid itemGuid;
    recv_data >> itemGuid;

    DEBUG_LOG("CMSG_ITEM_TEXT_QUERY item guid: %u", itemGuid.GetCounter());

    WorldPacket data(SMSG_ITEM_TEXT_QUERY_RESPONSE, (4 + 10)); // guess size

    if (Item* item = _player->GetItemByGuid(itemGuid))
    {
        data << uint8(0);                                   // has text
        data << ObjectGuid(itemGuid);                       // item guid
        data << item->GetText();
    }
    else
    {
        data << uint8(1);                                   // no text
    }
    SendPacket(&data);
}


void WorldSession::SendItemDb2Reply(uint32 entry)
{
    WorldPacket data(SMSG_DB_REPLY, 44);
    ItemPrototype const* proto = sObjectMgr.GetItemPrototype(entry);
    if (!proto)
    {
        data << uint32(-1);         // entry
        data << uint32(DB2_REPLY_ITEM);
        data << uint32(time(NULL)); // hotfix date
        data << uint32(0);          // size of next block
        SendPacket(&data);
        return;
    }

    data << uint32(entry);
    data << uint32(DB2_REPLY_ITEM);
    data << uint32(sObjectMgr.GetHotfixDate(entry, DB2_REPLY_ITEM));

    ByteBuffer buff;
    buff << uint32(entry);
    buff << uint32(proto->Class);
    buff << uint32(proto->SubClass);
    buff << int32(proto->Unk0);
    buff << uint32(proto->Material);
    buff << uint32(proto->DisplayInfoID);
    buff << uint32(proto->InventoryType);
    buff << uint32(proto->Sheath);

    data << uint32(buff.size());
    data.append(buff);

    SendPacket(&data);
}

void WorldSession::SendItemSparseDb2Reply(uint32 entry)
{
    WorldPacket data(SMSG_DB_REPLY, 526);
    ItemPrototype const* proto = sObjectMgr.GetItemPrototype(entry);
    if (!proto)
    {
        data << uint32(-1);         // entry
        data << uint32(DB2_REPLY_SPARSE);
        data << uint32(time(NULL)); // hotfix date
        data << uint32(0);          // size of next block
        SendPacket(&data);
        return;
    }

    data << uint32(entry);
    data << uint32(DB2_REPLY_SPARSE);
    data << uint32(sObjectMgr.GetHotfixDate(entry, DB2_REPLY_SPARSE));

    ByteBuffer buff;
    buff << uint32(entry);
    buff << uint32(proto->Quality);
    buff << uint32(proto->Flags);
    buff << uint32(proto->Flags2);
    buff << float(proto->Unknown);
    buff << float(proto->Unknown1);
    buff << uint32(proto->BuyCount);
    buff << int32(proto->BuyPrice);
    buff << uint32(proto->SellPrice);
    buff << uint32(proto->InventoryType);
    buff << int32(proto->AllowableClass);
    buff << int32(proto->AllowableRace);
    buff << uint32(proto->ItemLevel);
    buff << uint32(proto->RequiredLevel);
    buff << uint32(proto->RequiredSkill);
    buff << uint32(proto->RequiredSkillRank);
    buff << uint32(proto->RequiredSpell);
    buff << uint32(proto->RequiredHonorRank);
    buff << uint32(proto->RequiredCityRank);
    buff << uint32(proto->RequiredReputationFaction);
    buff << uint32(proto->RequiredReputationRank);
    buff << int32(proto->MaxCount);
    buff << int32(proto->Stackable);
    buff << uint32(proto->ContainerSlots);

    for (uint32 x = 0; x < MAX_ITEM_PROTO_STATS; ++x)
    {
        buff << uint32(proto->ItemStat[x].ItemStatType);
    }

    for (uint32 x = 0; x < MAX_ITEM_PROTO_STATS; ++x)
    {
        buff << int32(proto->ItemStat[x].ItemStatValue);
    }

    for (uint32 x = 0; x < MAX_ITEM_PROTO_STATS; ++x)
    {
        buff << int32(proto->ItemStat[x].ItemStatType2);
    }

    for (uint32 x = 0; x < MAX_ITEM_PROTO_STATS; ++x)
    {
        buff << int32(proto->ItemStat[x].ItemStatValue2);
    }

    buff << uint32(proto->ScalingStatDistribution);
    buff << uint32(proto->DamageType);
    buff << uint32(proto->Delay);
    buff << float(proto->RangedModRange);

    for (uint32 x = 0; x < MAX_ITEM_PROTO_SPELLS; ++x)
    {
        buff << int32(proto->Spells[x].SpellId);
    }

    for (uint32 x = 0; x < MAX_ITEM_PROTO_SPELLS; ++x)
    {
        buff << uint32(proto->Spells[x].SpellTrigger);
    }

    for (uint32 x = 0; x < MAX_ITEM_PROTO_SPELLS; ++x)
    {
        buff << int32(proto->Spells[x].SpellCharges);
    }

    for (uint32 x = 0; x < MAX_ITEM_PROTO_SPELLS; ++x)
    {
        buff << int32(proto->Spells[x].SpellCooldown);
    }

    for (uint32 x = 0; x < MAX_ITEM_PROTO_SPELLS; ++x)
    {
        buff << uint32(proto->Spells[x].SpellCategory);
    }

    for (uint32 x = 0; x < MAX_ITEM_PROTO_SPELLS; ++x)
    {
        buff << int32(proto->Spells[x].SpellCategoryCooldown);
    }

    buff << uint32(proto->Bonding);

    // item name
    std::string name = proto->Name1;
    buff << uint16(name.length());
    if (name.length())
    {
        buff << name;
    }

    for (uint32 i = 0; i < 3; ++i) // other 3 names
    {
        buff << uint16(0);
    }

    std::string desc = proto->Description;
    buff << uint16(desc.length());
    if (desc.length())
    {
        buff << desc;
    }

    buff << uint32(proto->PageText);
    buff << uint32(proto->LanguageID);
    buff << uint32(proto->PageMaterial);
    buff << uint32(proto->StartQuest);
    buff << uint32(proto->LockID);
    buff << int32(proto->Material);
    buff << uint32(proto->Sheath);
    buff << int32(proto->RandomProperty);
    buff << int32(proto->RandomSuffix);
    buff << uint32(proto->ItemSet);

    buff << uint32(proto->Area);
    buff << uint32(proto->Map);
    buff << uint32(proto->BagFamily);
    buff << uint32(proto->TotemCategory);

    for (uint32 x = 0; x < MAX_ITEM_PROTO_SOCKETS; ++x)
    {
        buff << uint32(proto->Socket[x].Color);
    }

    for (uint32 x = 0; x < MAX_ITEM_PROTO_SOCKETS; ++x)
    {
        buff << uint32(proto->Socket[x].Content);
    }

    buff << uint32(proto->socketBonus);
    buff << uint32(proto->GemProperties);
    buff << float(proto->ArmorDamageModifier);
    buff << int32(proto->Duration);
    buff << uint32(proto->ItemLimitCategory);
    buff << uint32(proto->HolidayId);
    buff << float(proto->StatScalingFactor);
    buff << uint32(proto->Unknown400_1);
    buff << uint32(proto->Unknown400_2);

    data << uint32(buff.size());
    data.append(buff);

    SendPacket(&data);
}

void WorldSession::SendReforgeResult(bool success)
{
    WorldPacket data(SMSG_REFORGE_RESULT, 1);
    data.WriteBit(success);
    SendPacket(&data);
}

void WorldSession::HandleReforgeItemOpcode(WorldPacket& recvData)
{
    uint32 slot, reforgeEntry;
    ObjectGuid guid;
    uint32 bag;
    Player* player = GetPlayer();

    recvData >> reforgeEntry >> slot >> bag;
    recvData.ReadGuidMask<2, 6, 3, 4, 1, 0, 7, 5>(guid);
    recvData.ReadGuidBytes<2, 3, 6, 4, 1, 0, 7, 5>(guid);

    if (!player->GetNPCIfCanInteractWith(guid, UNIT_NPC_FLAG_REFORGER))
    {
        sLog.outDebug("WORLD: HandleReforgeItemOpcode - Unit (GUID: %s) not found or player can't interact with it.", guid.GetString().c_str());
        SendReforgeResult(false);
        return;
    }

    Item* item = player->GetItemByPos(bag, slot);
    if (!item)
    {
        sLog.outDebug("WORLD: HandleReforgeItemOpcode - Player (Guid: %s) tried to reforge an invalid/non-existant item.", player->GetGuidStr().c_str());
        SendReforgeResult(false);
        return;
    }

    if (!reforgeEntry)
    {
        // Reset the item
        if (item->IsEquipped())
        {
            player->ApplyReforgeEnchantment(item, false);
        }

        item->ClearEnchantment(REFORGE_ENCHANTMENT_SLOT);
        SendReforgeResult(true);
        return;
    }

    ItemReforgeEntry const* stats = sItemReforgeStore.LookupEntry(reforgeEntry);
    if (!stats)
    {
        sLog.outDebug("WORLD: HandleReforgeItemOpcode - Player (Guid: %s) tried to reforge an item with invalid reforge entry (%u).", player->GetGuidStr().c_str(), reforgeEntry);
        SendReforgeResult(false);
        return;
    }

    if (!item->GetReforgableStat(ItemModType(stats->SourceStat)) || item->GetReforgableStat(ItemModType(stats->FinalStat))) // Cheating, you cant reforge to a stat that the item already has, nor reforge from a stat that the item does not have
    {
        SendReforgeResult(false);
        return;
    }

    if (player->GetMoney() < uint64(item->GetSpecialPrice()))   // cheating
    {
        SendReforgeResult(false);
        return;
    }

    player->ModifyMoney(-int64(item->GetSpecialPrice()));
    item->SetEnchantment(REFORGE_ENCHANTMENT_SLOT, reforgeEntry, 0, 0);
    SendReforgeResult(true);

    if (item->IsEquipped())
    {
        player->ApplyReforgeEnchantment(item, true);
    }
}

