
// -*- C++ -*-
// $Id: Version.h 97979 2014-11-14 07:38:51Z johnnyw $
// This is file was automatically generated by \$ACE_ROOT/bin/make_release.py

#define ACE_MAJOR_VERSION 6
#define ACE_MINOR_VERSION 3
#define ACE_BETA_VERSION 0
#define ACE_VERSION "6.3.0"
